### ISSUE TITLE
[Feature Request] Improvements to Japanese input

### ISSUE THREAD

**Issue by torakiti2017** [goatcorp/Dalamud#1498] opened 2023-10-21 06:44 UTC
- Use GoogleJapaneseIME.
- The same with Microsoft IME.

When typing in Japanese in the plugin window, text is also typed in the chat field.
Is it possible to prevent text from being entered in the chat field when entering text in the plugin field?
1.Entering text in the plugin window
<img width="447" alt="2" src="https://github.com/goatcorp/Dalamud/assets/86459831/0f70b7fc-3e29-45b6-824b-04333e6f9a2c">

2.Text is also entered in the chat field
<img width="192" alt="3" src="https://github.com/goatcorp/Dalamud/assets/86459831/ed61d157-7803-40b9-93d4-c342bfc86ab9">

Also, when I focus on the text input field in the plugin, the chat input afterwards is in half-width English characters. Since the input type in the chat field is double-byte, is it possible to force it not to be half-width English characters?
1.Click on the input field in the plugin window
<img width="447" alt="11" src="https://github.com/goatcorp/Dalamud/assets/86459831/018253f2-3961-4ff0-9106-9bb1e80e7d3b">

2.Click on the input field of the chat field
<img width="107" alt="12" src="https://github.com/goatcorp/Dalamud/assets/86459831/3661f79c-40a2-48ba-94e9-0f6b853b8de7">

3.input "s" and "a
<img width="80" alt="13" src="https://github.com/goatcorp/Dalamud/assets/86459831/b4adc524-ff40-4415-baa5-e2f223447cd2">
Half-width characters are entered.

4.The expected behaviour is that "さ" is entered
<img width="94" alt="14" src="https://github.com/goatcorp/Dalamud/assets/86459831/22abdc73-638f-4097-972f-3a025825f3e9">

**Comment by nebel** [comment] 2023-10-26 01:59
I tested this and wanted to provide more details.

> When typing in Japanese in the plugin window, text is also typed in the chat field.

I confirmed that this bug happens with the caveat that the chat window (or other native text input field) must be active (i.e. with a visible cursor) and using kana input for it to happen. Non-IME input doesn't behave this way and will only input to imgui.

> Also, when I focus on the text input field in the plugin, the chat input afterwards is in half-width English characters.

This bug is maybe worse than it sounds. The actual behavior seems to be something like this:

1. Focus any imgui text input. It doesn't matter if we're using kana or alpha input.
2. Focus a native text input. The input mode is stuck in alpha mode, meaning we can't enter kana even if we appear to be in kana mode (even if the input mode indicator says otherwise), and trying to switch between kana and alpha input also doesn't work (the keybind is seemingly ignored and the input mode indicator doesn't change).
3. Only by defocusing and refocusing a native text input is the abnormal state fixed.

No idea how to solve these issues yet.

**Comment by KazWolfe** [comment] 2024-01-08 04:08
Hi!

Thank you for opening this Issue. Given that a PR was merged mentioning this bug report, I'm going to go ahead and close this Issue. If you need further assistance or are still having problems, please feel free to reopen this Issue.

Thanks!

**Closed by KazWolfe** 2024-01-08 04:08 UTC
