### ISSUE TITLE
Crashes upon hitting Send button on a Report Harassment on Linux

### ISSUE THREAD

**Issue by Lexden12** [goatcorp/Dalamud#1242] opened 2023-06-07 04:40 UTC
When using the Support Desk to send a report of harassment to GMs, Dalamud crashes. See attached screenshot for the error reported. Note that this is on Ubuntu 23.04 using XIVLauncher's Wine/dxvk implementation. Tried multiple times and it was 100% reproducible.
![image](https://github.com/goatcorp/Dalamud/assets/24421791/c1efbd83-29c8-41a2-a8de-a38aa146af4e)

**Comment by NotNite** [comment] 2023-06-07 04:41
I think this is a duplicate of #1049?

**Comment by yaomtc** [comment] 2023-06-09 19:24
Yeah, you and I are both using Linux. Given nobody else has reported this issue, it must be specific to the Linux version, some Wine bug.

**Comment by NotNite** [comment] 2023-06-09 19:25
Certainly. I currently suspect this is an issue with SE's detection for Wine (Mac/Steam Deck), or an issue with making the HTTP request, but I haven't had time to look into it. I'll close this in favor of the other issue - feel free to post more information there.

**Closed by NotNite** 2023-06-09 19:25 UTC
